<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Communications{
 private static $instance;
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_post_zccng_create_broadcast',[$this,'create']);add_action('admin_post_zccng_broadcast_action',[$this,'change_status']);add_action('admin_post_zccng_message_action',[$this,'message_action']);}
 public static function priorities(){return ['information','attention','important','critical','success'];}
 public static function categories(){return ['operations','security','hr','training','compliance','department','recognition'];}
 public static function active_ticker(){global $wpdb;$t=$wpdb->prefix.'zccng_broadcasts';$now=current_time('mysql',true);return (array)$wpdb->get_results($wpdb->prepare("SELECT * FROM $t WHERE status='published' AND ticker_enabled=1 AND (publish_at IS NULL OR publish_at<=%s) AND (expires_at IS NULL OR expires_at>=%s) AND (audience='all' OR audience='staff') ORDER BY FIELD(priority,'critical','important','attention','information','success'),created_at DESC LIMIT 8",$now,$now),ARRAY_A);}
 public static function inbox($uid,$limit=20){global $wpdb;$b=$wpdb->prefix.'zccng_broadcasts';$r=$wpdb->prefix.'zccng_message_reads';$limit=max(1,min(100,(int)$limit));return (array)$wpdb->get_results($wpdb->prepare("SELECT b.*,IF(r.read_at IS NULL,0,1) is_read,IF(r.acknowledged_at IS NULL,0,1) is_acknowledged FROM $b b LEFT JOIN $r r ON r.broadcast_id=b.id AND r.user_id=%d WHERE b.status='published' AND r.archived_at IS NULL AND (b.audience='all' OR b.audience='staff') AND (b.publish_at IS NULL OR b.publish_at<=UTC_TIMESTAMP()) AND (b.expires_at IS NULL OR b.expires_at>=UTC_TIMESTAMP()) ORDER BY b.created_at DESC LIMIT %d",$uid,$limit),ARRAY_A);}
 public static function summary(){global $wpdb;$b=$wpdb->prefix.'zccng_broadcasts';return ['active'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $b WHERE status='published'"),'pending'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $b WHERE status='submitted'"),'scheduled'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $b WHERE status='scheduled'"),'critical'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $b WHERE status='published' AND priority='critical'")];}
 public static function recent($limit=20){global $wpdb;$t=$wpdb->prefix.'zccng_broadcasts';$limit=max(1,min(100,(int)$limit));return (array)$wpdb->get_results("SELECT * FROM $t ORDER BY created_at DESC LIMIT $limit",ARRAY_A);}
 public function create(){if(!Permissions::instance()->can('zccng_manage_broadcasts'))wp_die('Permission denied',403);check_admin_referer('zccng_create_broadcast');global $wpdb;$t=$wpdb->prefix.'zccng_broadcasts';$title=sanitize_text_field($_POST['title']??'');$message=sanitize_textarea_field($_POST['message']??'');if(!$title||!$message)wp_die('Title and message are required.',400);$priority=sanitize_key($_POST['priority']??'information');$category=sanitize_key($_POST['category']??'operations');$status=Permissions::instance()->can('zccng_publish_broadcasts')&&isset($_POST['publish_now'])?'published':'submitted';$wpdb->insert($t,['title'=>$title,'message'=>$message,'category'=>in_array($category,self::categories(),true)?$category:'operations','priority'=>in_array($priority,self::priorities(),true)?$priority:'information','audience'=>'all','status'=>$status,'ticker_enabled'=>isset($_POST['ticker_enabled'])?1:0,'created_by'=>get_current_user_id(),'approved_by'=>$status==='published'?get_current_user_id():0,'publish_at'=>$status==='published'?current_time('mysql',true):null,'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)],['%s','%s','%s','%s','%s','%s','%d','%d','%d','%s','%s','%s']);Audit::log('broadcast_created','Broadcast created',['broadcast_id'=>(int)$wpdb->insert_id,'status'=>$status]);wp_safe_redirect(admin_url('admin.php?page=zccng-operations&created=1'));exit;}
 public function change_status(){if(!Permissions::instance()->can('zccng_publish_broadcasts'))wp_die('Permission denied',403);$id=absint($_GET['id']??0);$action=sanitize_key($_GET['do']??'');check_admin_referer('zccng_broadcast_'.$id);if(!$id||!in_array($action,['publish','archive','ticker_on','ticker_off'],true))wp_die('Invalid request',400);global $wpdb;$t=$wpdb->prefix.'zccng_broadcasts';$data=$action==='publish'?['status'=>'published','approved_by'=>get_current_user_id(),'publish_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)]:($action==='archive'?['status'=>'archived','updated_at'=>current_time('mysql',true)]:['ticker_enabled'=>$action==='ticker_on'?1:0,'updated_at'=>current_time('mysql',true)]);$wpdb->update($t,$data,['id'=>$id]);Audit::log('broadcast_'.$action,'Broadcast '.($action==='publish'?'published':'archived'),['broadcast_id'=>$id]);wp_safe_redirect(admin_url('admin.php?page=zccng-operations'));exit;}
 public function message_action(){if(!is_user_logged_in())wp_die('Permission denied',403);$id=absint($_GET['id']??0);$do=sanitize_key($_GET['do']??'');check_admin_referer('zccng_message_'.$id);if(!$id||!in_array($do,['read','acknowledge','archive'],true))wp_die('Invalid request',400);global $wpdb;$t=$wpdb->prefix.'zccng_message_reads';$existing=$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE user_id=%d AND broadcast_id=%d",get_current_user_id(),$id),ARRAY_A);$data=['broadcast_id'=>$id,'user_id'=>get_current_user_id(),'read_at'=>$existing['read_at']??current_time('mysql',true),'acknowledged_at'=>$existing['acknowledged_at']??null,'archived_at'=>$existing['archived_at']??null];if($do==='acknowledge')$data['acknowledged_at']=current_time('mysql',true);if($do==='archive')$data['archived_at']=current_time('mysql',true);$wpdb->replace($t,$data,['%d','%d','%s','%s','%s']);Audit::log('message_'.$do,'Communication '.$do,['broadcast_id'=>$id]);wp_safe_redirect(admin_url('admin.php?page=zccng-staff-hub#zccng-inbox'));exit;} public static function render_ticker(){
 $items=self::active_ticker();if(!$items)return '';
 $first=$items[0];$out='<div class="zccng-ticker zccng-ticker--'.esc_attr($first['priority']).'" data-zccng-ticker><div class="zccng-ticker-label"><span class="zccng-ticker-beacon" aria-hidden="true"></span><b data-ticker-title>'.esc_html($first['title']).'</b></div><div class="zccng-ticker-window">';
 foreach($items as $n=>$i)$out.='<a class="zccng-ticker-message'.($n?'':' is-active').'" data-priority="'.esc_attr($i['priority']).'" data-title="'.esc_attr($i['title']).'" href="'.esc_url(admin_url('admin.php?page=zccng-staff-hub#zccng-inbox')).'"><span>'.esc_html($i['message']).'</span></a>';
 return $out.'</div></div>';
 }
}
