<?php
namespace ZCCNG;if(!defined('ABSPATH'))exit;
final class Repository{
 private static function exists($t){global $wpdb;return $wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$t))===$t;}private static function table($s){global $wpdb;return $wpdb->prefix.$s;}
 public static function recent_activity(){return Audit::recent(12);}public static function network_summary(){global $wpdb;$sites=get_sites(['number'=>0,'deleted'=>0,'spam'=>0,'archived'=>0]);$connected=$wpdb->base_prefix.'zccng_connected_sites';return ['sites'=>count($sites),'active_sites'=>count($sites),'users'=>(int)get_user_count(),'connected_sites'=>self::exists($connected)?(int)$wpdb->get_var("SELECT COUNT(*) FROM $connected WHERE status='approved'"):0];}
 public static function staff_summary(){$users=get_users(['number'=>200]);$online=[];$working=[];$leave=[];$now=time();foreach($users as $u){$last=(int)get_user_meta($u->ID,'zcc_last_seen',true);if($last&&$now-$last<900)$online[]=$u;$clock=get_user_meta($u->ID,'zcc_clock_status',true);if(in_array($clock,['clocked_in','on_break'],true))$working[]=$u;}global $wpdb;$t=self::table('zcc_leave_requests');if(self::exists($t))$leave=(array)$wpdb->get_results("SELECT user_id,start_date,end_date,leave_type,status FROM $t WHERE status='approved' AND CURDATE() BETWEEN start_date AND end_date ORDER BY start_date LIMIT 20",ARRAY_A);return ['staff_count'=>count($users),'online_count'=>count($online),'working_count'=>count($working),'leave_count'=>count($leave),'online'=>$online,'working'=>$working,'leave'=>$leave];}
 public static function profile($id){$u=get_userdata($id);if(!$u)return [];global $wpdb;$hr=[];$hours=0;$unread=0;$leave=[];$t=self::table('zcc_hr_records');if(self::exists($t))$hr=(array)$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE user_id=%d LIMIT 1",$id),ARRAY_A);$t=self::table('zcc_timesheets');if(self::exists($t))$hours=(float)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(total_hours),0) FROM $t WHERE user_id=%d AND clock_in>=DATE_SUB(CURDATE(),INTERVAL WEEKDAY(CURDATE()) DAY)",$id));$t=self::table('zcc_notifications');if(self::exists($t))$unread=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $t WHERE user_id=%d AND is_read=0",$id));$t=self::table('zcc_leave_requests');if(self::exists($t))$leave=(array)$wpdb->get_results($wpdb->prepare("SELECT leave_type,start_date,end_date,status FROM $t WHERE user_id=%d ORDER BY created_at DESC LIMIT 5",$id),ARRAY_A);return ['name'=>$u->display_name,'email'=>$u->user_email,'avatar'=>get_avatar_url($id,['size'=>160]),'roles'=>$u->roles,'hr'=>$hr,'hours_week'=>$hours,'unread'=>$unread,'leave'=>$leave,'clock_status'=>(string)get_user_meta($id,'zcc_clock_status',true)];}
 public static function support_summary(){global $wpdb;$t=self::table('zcc_support_tickets');if(!self::exists($t))return ['available'=>false,'open'=>0,'progress'=>0,'critical'=>0,'breached'=>0,'tickets'=>[]];$uid=get_current_user_id();$scope=Permissions::instance()->can('zccng_view_all_support')?'1=1':$wpdb->prepare('(created_by=%d OR assigned_to=%d)',$uid,$uid);return ['available'=>true,'open'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE $scope AND status='open'"),'progress'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE $scope AND status='in_progress'"),'critical'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE $scope AND priority='critical' AND status NOT IN ('closed','resolved')"),'breached'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE $scope AND sla_deadline IS NOT NULL AND sla_deadline<NOW() AND status NOT IN ('closed','resolved')"),'tickets'=>(array)$wpdb->get_results("SELECT id,ticket_number,subject,status,priority,created_at FROM $t WHERE $scope AND status NOT IN ('closed','resolved') ORDER BY FIELD(priority,'critical','high','medium','low'),created_at ASC LIMIT 10",ARRAY_A)];}
 public static function hr_summary(){global $wpdb;$h=self::table('zcc_hr_records');$l=self::table('zcc_leave_requests');$t=self::table('zcc_timesheets');return ['records'=>self::exists($h)?(int)$wpdb->get_var("SELECT COUNT(*) FROM $h"):0,'pending_leave'=>self::exists($l)?(int)$wpdb->get_var("SELECT COUNT(*) FROM $l WHERE status='pending'"):0,'timesheets_review'=>self::exists($t)?(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE status='submitted'"):0,'new_starters'=>self::exists($h)?(int)$wpdb->get_var("SELECT COUNT(*) FROM $h WHERE hire_date>=DATE_SUB(CURDATE(),INTERVAL 30 DAY)"):0,'staff'=>self::exists($h)?(array)$wpdb->get_results("SELECT user_id,department,job_title,employment_type FROM $h ORDER BY updated_at DESC LIMIT 12",ARRAY_A):[]];}
 public static function operations_summary(){return Communications::summary();}
 public static function communications_inbox($id,$limit=20){return Communications::inbox((int)$id,(int)$limit);}
 public static function broadcasts($limit=20){return Communications::recent((int)$limit);}
 public static function candidate_summary(){return Candidates::summary();} public static function candidates($limit=100){return Candidates::all($limit);} public static function candidate($id){return Candidates::get((int)$id);} public static function form_summary(){return Forms::summary();} public static function form_templates(){return Forms::templates();} public static function form_submissions($limit=100){return Forms::submissions($limit);}}
