<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Workforce_Mail{
 private static $instance;
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_init',[$this,'legacy_redirect']);add_action('admin_post_zccng_save_work_email',[$this,'save_work_email']);add_action('admin_post_zccng_send_work_email',[$this,'send_work_email']);add_action('admin_post_zccng_batch_work_email',[$this,'batch_email']);}
 public function legacy_redirect(){if(!is_admin()||empty($_GET['page']))return;$page=sanitize_key(wp_unslash($_GET['page']));$map=['zccng-employment-email'=>['zccng-hr','communications'],'zccng-batch-email'=>['zccng-operations','email'],'zccng-my-work-email'=>['zccng-profile','employment']];if(!isset($map[$page]))return;[$target,$section]=$map[$page];wp_safe_redirect(admin_url('admin.php?page='.$target.'&zcc_page='.$section));exit;}
 private static function allowed_manage(){return is_super_admin()||current_user_can('zccng_manage_hr')||current_user_can('zccng_manage_candidates');}
 private static function staff_users(){return get_users(['role__not_in'=>['zccng_candidate'],'orderby'=>'display_name','order'=>'ASC']);}
 public static function address($uid){return sanitize_email((string)get_user_meta($uid,'zccng_work_email',true));}
 public static function status($uid){$s=(string)get_user_meta($uid,'zccng_work_email_status',true);return in_array($s,['active','suspended','closed'],true)?$s:'not_provisioned';}
 public function save_work_email(){if(!self::allowed_manage())wp_die('Not allowed');check_admin_referer('zccng_save_work_email');$uid=absint($_POST['user_id']??0);$email=sanitize_email(wp_unslash($_POST['work_email']??''));$status=sanitize_key($_POST['work_email_status']??'active');if(!$uid||!get_userdata($uid)||!in_array($status,['active','suspended','closed'],true))wp_die('Invalid employment email record');update_user_meta($uid,'zccng_work_email',$email);update_user_meta($uid,'zccng_work_email_status',$status);update_user_meta($uid,'zccng_work_email_updated_at',current_time('mysql',true));Audit::log('work_email_updated','Employment email updated',['user_id'=>$uid,'status'=>$status]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr&zcc_page=communications&updated=1'));exit;}
 public function send_work_email(){if(!self::allowed_manage())wp_die('Not allowed');check_admin_referer('zccng_send_work_email');$uid=absint($_POST['user_id']??0);$u=get_userdata($uid);$email=self::address($uid);if(!$u||!$email)wp_die('Employment email is not provisioned');$subject=sanitize_text_field(wp_unslash($_POST['subject']??'Your employment email'));$body=sanitize_textarea_field(wp_unslash($_POST['message']??''));$sent=wp_mail($u->user_email,$subject,$body."\n\nEmployment email: ".$email."\nLogin: ".wp_login_url());update_user_meta($uid,'zccng_work_email_notice_status',$sent?'processed':'failed');update_user_meta($uid,'zccng_work_email_notice_at',current_time('mysql',true));Audit::log($sent?'work_email_notice_sent':'work_email_notice_failed','Employment email notice processed',['user_id'=>$uid]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr&zcc_page=communications&mail='.($sent?'processed':'failed')));exit;}
 public function batch_email(){if(!(is_super_admin()||current_user_can('zccng_send_batch_messages')))wp_die('Not allowed');check_admin_referer('zccng_batch_work_email');$subject=sanitize_text_field(wp_unslash($_POST['subject']??''));$message=sanitize_textarea_field(wp_unslash($_POST['message']??''));if(!$subject||!$message)wp_die('Subject and message are required');$sent=0;$failed=0;foreach(self::staff_users() as $u){$target=self::address($u->ID);if(self::status($u->ID)!=='active'||!$target)continue;if(wp_mail($target,$subject,$message))$sent++;else$failed++;}Audit::log('workforce_batch_email','Operations batch email processed',['sent'=>$sent,'failed'=>$failed]);wp_safe_redirect(admin_url('admin.php?page=zccng-operations&zcc_page=email&sent='.$sent.'&failed='.$failed));exit;}
 public static function render_staff_panel(){$uid=get_current_user_id();$e=self::address($uid);$s=self::status($uid);return '<div class="zccng-work-email-card"><h3>'.($e?esc_html($e):'Not yet provisioned').'</h3><p>Status: <strong>'.esc_html(ucwords(str_replace('_',' ',$s))).'</strong></p><p>Company email is provided for employment and business use only.</p><p><a class="zccng-button" href="'.esc_url(admin_url('admin.php?page=zccng-staff-hub&zcc_page=messages')).'">Open Workforce Inbox</a></p></div>';}
 public static function render_operations_panel(){if(!(is_super_admin()||current_user_can('zccng_send_batch_messages')))return '<div class="zccng-empty">You do not have permission to send workforce batch email.</div>';$notice='';if(isset($_GET['sent']))$notice='<div class="notice notice-success inline"><p>Processed: '.absint($_GET['sent']).' sent, '.absint($_GET['failed']??0).' failed.</p></div>';return $notice.'<form class="zccng-broadcast-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('zccng_batch_work_email','_wpnonce',true,false).'<input type="hidden" name="action" value="zccng_batch_work_email"><label>Subject<input type="text" name="subject" required></label><label>Message<textarea name="message" rows="10" required></textarea></label><p class="description">Recipients are active employees with a provisioned employment email. Individual selection is intentionally unavailable.</p><button class="zccng-button">Send to all active employees</button></form>';}
 public static function render_hr_panel(){if(!self::allowed_manage())return '<div class="zccng-empty">You do not have permission to manage employment email.</div>';$out='<div class="zccng-grid zccng-employment-email-grid">';foreach(self::staff_users() as $u){$e=self::address($u->ID);$s=self::status($u->ID);$out.='<section class="zccng-panel-body"><h3>'.esc_html($u->display_name).'</h3><p>'.esc_html($u->user_email).'</p><form class="zccng-broadcast-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('zccng_save_work_email','_wpnonce',true,false).'<input type="hidden" name="action" value="zccng_save_work_email"><input type="hidden" name="user_id" value="'.(int)$u->ID.'"><label>Employment email<input type="email" name="work_email" value="'.esc_attr($e).'" placeholder="name@company.com"></label><label>Status<select name="work_email_status">';foreach(['active','suspended','closed'] as $v)$out.='<option value="'.$v.'" '.selected($s,$v,false).'>'.esc_html(ucfirst($v)).'</option>';$out.='</select></label><button class="zccng-button">Save</button></form>';if($e)$out.='<form class="zccng-inline-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('zccng_send_work_email','_wpnonce',true,false).'<input type="hidden" name="action" value="zccng_send_work_email"><input type="hidden" name="user_id" value="'.(int)$u->ID.'"><input type="hidden" name="subject" value="Your employment email is ready"><input type="hidden" name="message" value="Your business-use employment email has been provisioned."><button class="zccng-button zccng-button--light">Send activation details</button></form>';$out.='</section>'; }return $out.'</div>';}
 private function head($title,$text){echo '<div class="wrap zccng-app"><div class="zccng-hero"><h1>'.esc_html($title).'</h1><p>'.esc_html($text).'</p></div>';}
 public function hr_page(){if(!self::allowed_manage())wp_die('Not allowed');$this->head('Employment Email Provisioning','Assign business-only domain email addresses after hiring.');echo '<div class="zccng-grid">';foreach(self::staff_users() as $u){$e=self::address($u->ID);$s=self::status($u->ID);echo '<section class="zccng-panel"><h2>'.esc_html($u->display_name).'</h2><p>'.esc_html($u->user_email).'</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('zccng_save_work_email');echo '<input type="hidden" name="action" value="zccng_save_work_email"><input type="hidden" name="user_id" value="'.(int)$u->ID.'"><label>Employment email<input type="email" name="work_email" value="'.esc_attr($e).'" placeholder="name@company.com"></label><label>Status<select name="work_email_status">';foreach(['active','suspended','closed'] as $v)echo '<option value="'.$v.'" '.selected($s,$v,false).'>'.esc_html(ucfirst($v)).'</option>';echo '</select></label><button class="zccng-button">Save</button></form>';if($e){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('zccng_send_work_email');echo '<input type="hidden" name="action" value="zccng_send_work_email"><input type="hidden" name="user_id" value="'.(int)$u->ID.'"><input type="hidden" name="subject" value="Your employment email is ready"><input type="hidden" name="message" value="Your business-use employment email has been provisioned."><button class="zccng-button zccng-button--ghost">Send activation details</button></form>';}echo '</section>';}echo '</div></div>';}
 public function operations_page(){if(!(is_super_admin()||current_user_can('zccng_send_batch_messages')))wp_die('Not allowed');$this->head('Workforce Batch Email','Operations Officers can send batch messages to all active provisioned employees only.');if(isset($_GET['sent']))echo '<div class="notice notice-success"><p>Processed: '.absint($_GET['sent']).' sent, '.absint($_GET['failed']??0).' failed.</p></div>';echo '<section class="zccng-panel"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('zccng_batch_work_email');echo '<input type="hidden" name="action" value="zccng_batch_work_email"><label>Subject<input type="text" name="subject" required></label><label>Message<textarea name="message" rows="10" required></textarea></label><p class="description">Recipients are active employees with a provisioned employment email. Individual selection is intentionally unavailable.</p><button class="zccng-button">Send to all active employees</button></form></section></div>';}
 public function staff_page(){$uid=get_current_user_id();$e=self::address($uid);$s=self::status($uid);$this->head('My Work Email','Employment communications and business-use email status.');echo '<section class="zccng-panel"><h2>'.($e?esc_html($e):'Not yet provisioned').'</h2><p>Status: <strong>'.esc_html(ucwords(str_replace('_',' ',$s))).'</strong></p><p>Company email is provided for employment and business use only. Personal use is not permitted.</p><p><a class="zccng-button" href="'.esc_url(admin_url('admin.php?page=zccng-staff-hub')).'">Open Workforce Inbox</a></p></section></div>';}
}
