<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Core_Settings{
 private static $instance; const OPT='zccng_core_experience_v1'; const BAK='zccng_core_experience_v1_backup';
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_enqueue_scripts',[$this,'assets'],100);add_action('admin_menu',[$this,'menus'],42);add_action('network_admin_menu',[$this,'menus'],42);add_action('admin_post_zccng_save_core_experience',[$this,'save']);add_action('admin_post_zccng_save_role_controls',[$this,'save_roles']);}
 private function command_ok(){return is_super_admin()||current_user_can('zccng_manage_command_settings')||current_user_can('zccng_manage_ticker');}
 private function workforce_ok(){return is_super_admin()||current_user_can('zccng_manage_workforce_settings')||current_user_can('zccng_manage_lifecycle');}
 public static function defaults(){return ['speed'=>32,'delay'=>5,'direction'=>'rtl','animation'=>'scroll','font'=>'system','size'=>14,'weight'=>700,'spacing'=>0,'uppercase'=>0,'background'=>'#07101f','text'=>'#ffffff','title'=>'#ffffff','accent'=>'#36c5ff','height'=>'standard','pause'=>1,'immersive'=>1,'footer'=>1];}
 public static function settings(){return array_merge(self::defaults(),(array)get_site_option(self::OPT,[]));}

 public function assets(){if(!isset($_GET['page'])||strpos(sanitize_key($_GET['page']),'zccng-')!==0)return;$can_escape=is_super_admin()||current_user_can('zccng_access_nexus');$target=(is_super_admin()||current_user_can('zccng_access_nexus'))?network_admin_url('index.php'):admin_url('index.php');$target=wp_nonce_url(add_query_arg('zccng_main_admin','1',$target),'zccng_main_admin');wp_localize_script('zccng-app','ZCCNGCore',['settings'=>self::settings(),'adminUrl'=>$target,'canEscape'=>$can_escape]);}
 public function menus(){if($this->command_ok())add_submenu_page('zccng-home','Command Experience','Command Experience','read','zccng-command-settings',[$this,'command_page']);if($this->workforce_ok())add_submenu_page('zccng-home','Workforce Role Controls','Workforce Role Controls','read','zccng-workforce-role-controls',[$this,'role_page']);}
 private function head($title,$copy){echo '<div class="wrap zccng-settings-wrap"><h1>'.esc_html($title).'</h1><p>'.esc_html($copy).'</p>';if(isset($_GET['updated']))echo '<div class="notice notice-success"><p>Settings saved.</p></div>';}
 public function command_page(){if(!$this->command_ok())wp_die('Not allowed',403);$o=self::settings();$this->head('ZCCNG Command Experience','Core ticker and command-shell presentation settings.');echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('zccng_save_core_experience');echo '<input type="hidden" name="action" value="zccng_save_core_experience"><table class="form-table">';
 $fields=['speed'=>['Scroll duration','number'],'delay'=>['Rotation delay','number'],'size'=>['Font size','number'],'weight'=>['Font weight','number'],'spacing'=>['Letter spacing','number'],'background'=>['Background','color'],'text'=>['Message color','color'],'title'=>['Title color','color'],'accent'=>['Accent color','color']];foreach($fields as $k=>$f)echo '<tr><th>'.$f[0].'</th><td><input type="'.$f[1].'" name="'.$k.'" value="'.esc_attr($o[$k]).'"></td></tr>';
 foreach(['direction'=>['Direction',['rtl','ltr','ttb','btt','static']],'animation'=>['Animation',['scroll','slide','fade','pulse','static']],'font'=>['Font',['system','inter','arial','georgia','mono']],'height'=>['Height',['compact','standard','expanded']]] as $k=>$d){echo '<tr><th>'.$d[0].'</th><td><select name="'.$k.'">';foreach($d[1] as $v)echo '<option value="'.$v.'" '.selected($o[$k],$v,false).'>'.esc_html(ucwords(str_replace('_',' ',$v))).'</option>';echo '</select></td></tr>';}
 foreach(['uppercase'=>'Uppercase ticker text','pause'=>'Pause ticker on hover','immersive'=>'Full-width command interface','footer'=>'Show ZinControlCenter footer'] as $k=>$label)echo '<tr><th>'.$label.'</th><td><input type="checkbox" name="'.$k.'" value="1" '.checked(!empty($o[$k]),true,false).'></td></tr>';echo '</table>';submit_button();echo '</form></div>';}
 public function save(){if(!$this->command_ok())wp_die('Not allowed',403);check_admin_referer('zccng_save_core_experience');$old=self::settings();$pick=function($k,$a,$d){$v=sanitize_key($_POST[$k]??$d);return in_array($v,$a,true)?$v:$d;};$color=function($k,$d){return sanitize_hex_color($_POST[$k]??'')?:$d;};$n=['speed'=>max(5,min(120,absint($_POST['speed']??32))),'delay'=>max(1,min(30,absint($_POST['delay']??5))),'direction'=>$pick('direction',['rtl','ltr','ttb','btt','static'],'rtl'),'animation'=>$pick('animation',['scroll','slide','fade','pulse','static'],'scroll'),'font'=>$pick('font',['system','inter','arial','georgia','mono'],'system'),'size'=>max(11,min(28,absint($_POST['size']??14))),'weight'=>max(400,min(900,absint($_POST['weight']??700))),'spacing'=>max(0,min(6,absint($_POST['spacing']??0))),'background'=>$color('background','#07101f'),'text'=>$color('text','#ffffff'),'title'=>$color('title','#ffffff'),'accent'=>$color('accent','#36c5ff'),'height'=>$pick('height',['compact','standard','expanded'],'standard')];foreach(['uppercase','pause','immersive','footer'] as $k)$n[$k]=isset($_POST[$k])?1:0;update_site_option(self::BAK,['saved_at'=>current_time('mysql',true),'saved_by'=>get_current_user_id(),'settings'=>$old]);update_site_option(self::OPT,$n);foreach(['direction','speed','delay'] as $k)update_site_option('zccng_ticker_'.$k,$n[$k]);Audit::log('core_experience_updated','Core command experience updated');wp_safe_redirect(admin_url('admin.php?page=zccng-command-settings&updated=1'));exit;}
 public function role_page(){if(!$this->workforce_ok())wp_die('Not allowed',403);$this->head('ZCCNG Workforce Role Controls','Classify people without replacing their permission-bearing WordPress roles.');$classes=['employee'=>'Employee','volunteer'=>'Volunteer','applicant'=>'Applicant','candidate'=>'Candidate','contractor'=>'Contractor'];echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('zccng_save_role_controls');echo '<input type="hidden" name="action" value="zccng_save_role_controls"><table class="widefat striped"><thead><tr><th>Person</th><th>WordPress role</th><th>Workforce classification</th></tr></thead><tbody>';foreach(get_users(['number'=>500,'orderby'=>'display_name']) as $u){$cur=get_user_meta($u->ID,'zccng_workforce_classification',true)?:'employee';echo '<tr><td>'.esc_html($u->display_name).'<input type="hidden" name="users[]" value="'.(int)$u->ID.'"></td><td>'.esc_html(implode(', ',$u->roles)).'</td><td><select name="classification['.(int)$u->ID.']">';foreach($classes as $k=>$v)echo '<option value="'.$k.'" '.selected($cur,$k,false).'>'.$v.'</option>';echo '</select></td></tr>';}echo '</tbody></table>';submit_button('Save workforce classifications');echo '</form></div>';}
 public function save_roles(){if(!$this->workforce_ok())wp_die('Not allowed',403);check_admin_referer('zccng_save_role_controls');$allowed=['employee','volunteer','applicant','candidate','contractor'];foreach((array)($_POST['users']??[]) as $id){$id=absint($id);$v=sanitize_key($_POST['classification'][$id]??'employee');if($id&&in_array($v,$allowed,true))update_user_meta($id,'zccng_workforce_classification',$v);}Audit::log('workforce_classifications_updated','Workforce classifications updated');wp_safe_redirect(admin_url('admin.php?page=zccng-workforce-role-controls&updated=1'));exit;}

}
