<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Knowledge{
 private static $instance;
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_post_zccng_knowledge_save',[$this,'save']);add_action('admin_post_zccng_knowledge_archive',[$this,'archive']);}
 private static function table(){global $wpdb;return $wpdb->prefix.'zccng_knowledge';}
 public static function types(){return ['policy'=>'Policy','procedure'=>'Procedure','guide'=>'Guide','video'=>'Video','faq'=>'FAQ','best_practice'=>'Best Practice','reference'=>'Reference'];}
 public static function entries($published=true,$limit=200){global $wpdb;$limit=max(1,min(500,(int)$limit));$sql='SELECT * FROM '.self::table();if($published)$sql.=" WHERE status='published'";$sql.=' ORDER BY is_featured DESC,updated_at DESC LIMIT '.$limit;return (array)$wpdb->get_results($sql,ARRAY_A);}
 public static function counts(){global $wpdb;$t=self::table();return ['published'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE status='published'"),'draft'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE status='draft'"),'featured'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE status='published' AND is_featured=1"),'archived'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE status='archived'")];}
 public static function render_center(){if(!is_user_logged_in())return '';$rows=self::entries(true);$html='<div class="zccng-list zccng-knowledge-list">';if(!$rows)$html.='<div class="zccng-empty">No knowledge articles are published.</div>';foreach($rows as $row){$html.='<article><div><strong>'.esc_html($row['title']).'</strong><small>'.esc_html((self::types()[$row['content_type']]??ucwords($row['content_type'])).($row['is_featured']?' · Featured':'')).'</small><p>'.esc_html($row['summary']).'</p>'.($row['external_url']?'<a href="'.esc_url($row['external_url']).'" target="_blank" rel="noopener noreferrer">Open resource</a>':'').'</div></article>';}$html.='</div>';return $html;}
 public function save(){if(!Permissions::instance()->can('zccng_manage_knowledge'))wp_die('Forbidden',403);check_admin_referer('zccng_knowledge_save');$title=sanitize_text_field($_POST['title']??'');if(!$title)wp_die('Title required.');$type=sanitize_key($_POST['content_type']??'guide');if(!array_key_exists($type,self::types()))$type='guide';global $wpdb;$wpdb->insert(self::table(),['title'=>$title,'summary'=>sanitize_textarea_field($_POST['summary']??''),'content_body'=>wp_kses_post($_POST['content_body']??''),'content_type'=>$type,'category'=>sanitize_text_field($_POST['category']??''),'tags'=>sanitize_text_field($_POST['tags']??''),'external_url'=>esc_url_raw($_POST['external_url']??''),'status'=>!empty($_POST['publish'])?'published':'draft','is_featured'=>!empty($_POST['is_featured'])?1:0,'created_by'=>get_current_user_id(),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)]);Audit::log('knowledge_created','Knowledge Center entry created',['knowledge_id'=>$wpdb->insert_id,'type'=>$type]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr'));exit;}
 public function archive(){if(!Permissions::instance()->can('zccng_manage_knowledge'))wp_die('Forbidden',403);$id=absint($_GET['id']??0);check_admin_referer('zccng_knowledge_archive_'.$id);global $wpdb;$wpdb->update(self::table(),['status'=>'archived','updated_at'=>current_time('mysql',true)],['id'=>$id]);Audit::log('knowledge_archived','Knowledge Center entry archived',['knowledge_id'=>$id]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr'));exit;}
}
