<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Security{
 private static $instance;
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_post_zccng_security_alert',[$this,'save_alert']);add_action('admin_post_zccng_security_report',[$this,'report']);add_action('admin_post_zccng_security_resolve',[$this,'resolve']);add_action('admin_post_zccng_security_feed',[$this,'save_feed']);}
 private static function alerts_table(){global $wpdb;return $wpdb->prefix.'zccng_security_alerts';}
 private static function reports_table(){global $wpdb;return $wpdb->prefix.'zccng_security_reports';}
 public static function severities(){return ['critical','high','advisory','information','secure'];}
 public static function sources(){return ['FTC Consumer Alerts'=>'https://consumer.ftc.gov/consumer-alerts','CISA Cybersecurity Alerts & Advisories'=>'https://www.cisa.gov/news-events/cybersecurity-advisories','FBI Common Frauds and Scams'=>'https://www.fbi.gov/how-we-can-help-you/common-frauds-and-scams'];}
 public static function active_alerts($limit=12){global $wpdb;$limit=max(1,min(50,(int)$limit));return (array)$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::alerts_table()." WHERE status='published' AND (expires_at IS NULL OR expires_at='' OR expires_at>=UTC_TIMESTAMP()) ORDER BY FIELD(severity,'critical','high','advisory','information','secure'),published_at DESC LIMIT %d",$limit),ARRAY_A);}
 public static function reports($limit=100){global $wpdb;$limit=max(1,min(200,(int)$limit));return (array)$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::reports_table().' ORDER BY created_at DESC LIMIT %d',$limit),ARRAY_A);}
 public static function counts(){global $wpdb;$out=['critical'=>0,'high'=>0,'advisory'=>0,'information'=>0,'secure'=>0,'open_reports'=>0];foreach((array)$wpdb->get_results("SELECT severity,COUNT(*) total FROM ".self::alerts_table()." WHERE status='published' GROUP BY severity",ARRAY_A) as $row){$k=sanitize_key($row['severity']);if(isset($out[$k]))$out[$k]=(int)$row['total'];}$out['open_reports']=(int)$wpdb->get_var("SELECT COUNT(*) FROM ".self::reports_table()." WHERE status IN ('new','reviewing','investigating')");return $out;}
 public static function render_watch(){if(!is_user_logged_in())return '';$alerts=self::active_alerts();$html='<div class="zccng-list zccng-security-watch">';if(!$alerts)$html.='<div class="zccng-empty">No active security alerts.</div>';foreach($alerts as $a){$html.='<article class="zccng-security-alert zccng-security-alert--'.esc_attr($a['severity']).'"><span class="zccng-security-beacon" aria-hidden="true"></span><div><strong>'.esc_html($a['title']).'</strong><small>'.esc_html(ucwords($a['severity']).' · '.$a['source_name']).'</small><p>'.esc_html($a['summary']).'</p>'.($a['source_url']?'<a href="'.esc_url($a['source_url']).'" target="_blank" rel="noopener noreferrer">View official source</a>':'').'</div></article>';}$html.='</div><form class="zccng-broadcast-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="zccng_security_report">'.wp_nonce_field('zccng_security_report','_wpnonce',true,false).'<label>Report suspicious activity<textarea name="details" required placeholder="Describe the suspicious email, link, message, or activity."></textarea></label><label>Related URL or sender<input name="related_value"></label><button class="zccng-button" type="submit">Submit security report</button></form>';return $html;}
 public function save_alert(){if(!Permissions::instance()->can('zccng_manage_security'))wp_die('Forbidden',403);check_admin_referer('zccng_security_alert');$severity=sanitize_key($_POST['severity']??'information');if(!in_array($severity,self::severities(),true))$severity='information';$title=sanitize_text_field($_POST['title']??'');if(!$title)wp_die('Alert title is required.');global $wpdb;$wpdb->insert(self::alerts_table(),['title'=>$title,'summary'=>sanitize_textarea_field($_POST['summary']??''),'severity'=>$severity,'source_name'=>sanitize_text_field($_POST['source_name']??'Internal Security'),'source_url'=>esc_url_raw($_POST['source_url']??''),'status'=>!empty($_POST['publish'])?'published':'draft','published_at'=>current_time('mysql',true),'expires_at'=>sanitize_text_field($_POST['expires_at']??''),'created_by'=>get_current_user_id(),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)]);Audit::log('security_alert_created','Security awareness alert created',['alert_id'=>$wpdb->insert_id,'severity'=>$severity]);wp_safe_redirect(admin_url('admin.php?page=zccng-operations'));exit;}
 public function report(){if(!is_user_logged_in())wp_die('Authentication required.');check_admin_referer('zccng_security_report');global $wpdb;$wpdb->insert(self::reports_table(),['reported_by'=>get_current_user_id(),'details'=>sanitize_textarea_field($_POST['details']??''),'related_value'=>sanitize_text_field($_POST['related_value']??''),'status'=>'new','assigned_to'=>0,'resolution'=>'','created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)]);Audit::log('security_report_submitted','Suspicious activity reported',['report_id'=>$wpdb->insert_id]);wp_safe_redirect(admin_url('admin.php?page=zccng-staff'));exit;}
 public function resolve(){if(!Permissions::instance()->can('zccng_manage_security'))wp_die('Forbidden',403);check_admin_referer('zccng_security_resolve');$id=absint($_POST['report_id']??0);$status=sanitize_key($_POST['status']??'reviewing');if(!in_array($status,['reviewing','investigating','resolved','archived'],true))wp_die('Invalid status.');global $wpdb;$wpdb->update(self::reports_table(),['status'=>$status,'assigned_to'=>get_current_user_id(),'resolution'=>sanitize_textarea_field($_POST['resolution']??''),'updated_at'=>current_time('mysql',true)],['id'=>$id]);Audit::log('security_report_'.$status,'Security report status updated',['report_id'=>$id]);wp_safe_redirect(admin_url('admin.php?page=zccng-operations'));exit;}
 public function save_feed(){if(!Permissions::instance()->can('zccng_manage_security'))wp_die('Forbidden',403);check_admin_referer('zccng_security_feed');$feeds=array_filter(array_map('esc_url_raw',preg_split('/\R/',(string)($_POST['feed_urls']??''))));update_option('zccng_security_feed_urls',array_values($feeds),false);Audit::log('security_feeds_updated','Security RSS sources updated',['count'=>count($feeds)]);wp_safe_redirect(admin_url('admin.php?page=zccng-operations'));exit;}
}
