<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Lifecycle{
 private static $instance;
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_post_zccng_lifecycle_stage',[$this,'change_stage']);add_action('set_user_role',[$this,'role_changed'],20,3);}
 private static function table(){global $wpdb;return $wpdb->prefix.'zccng_lifecycle_events';}
 public static function stages(){return ['candidate'=>'Candidate','onboarding'=>'Onboarding','employee'=>'Employee','leave'=>'Leave','former_employee'=>'Former Employee','talent_pool'=>'Talent Pool','alumni'=>'Alumni','retired'=>'Retired','archived'=>'Archived'];}
 public static function current_stage($uid){$stage=sanitize_key(get_user_meta($uid,'zccng_lifecycle_stage',true));if(isset(self::stages()[$stage]))return $stage;$u=get_userdata($uid);if(!$u)return 'archived';if(in_array('zccng_candidate',(array)$u->roles,true))return 'candidate';if(in_array('zccng_staff',(array)$u->roles,true))return 'employee';return 'onboarding';}
 public static function record($uid,$event,$summary,$context=[],$actor=0){global $wpdb;$uid=absint($uid);if(!$uid)return false;return $wpdb->insert(self::table(),['user_id'=>$uid,'event_type'=>sanitize_key($event),'summary'=>sanitize_text_field($summary),'context_json'=>wp_json_encode($context),'actor_id'=>$actor?:get_current_user_id(),'created_at'=>current_time('mysql',true)]);}
 public static function timeline($uid,$limit=200){global $wpdb;$limit=max(1,min(500,(int)$limit));$events=(array)$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::table().' WHERE user_id=%d ORDER BY created_at DESC LIMIT %d',$uid,$limit),ARRAY_A);$audit=$wpdb->prefix.'zccng_audit_log';if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$audit))===$audit){foreach((array)$wpdb->get_results($wpdb->prepare("SELECT event_type,summary,context,created_at,user_id actor_id FROM $audit WHERE context LIKE %s ORDER BY created_at DESC LIMIT 100",'%\"user_id\":'.$uid.'%'),ARRAY_A) as $row){$row['context_json']=$row['context'];$events[]=$row;}}usort($events,static fn($a,$b)=>strcmp($b['created_at'],$a['created_at']));return array_slice($events,0,$limit);}
 private static function count_table($table,$where,$uid){global $wpdb;if($wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))!==$table)return 0;return (int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $table WHERE $where",$uid));}
 public static function snapshot($uid){global $wpdb;return ['stage'=>self::current_stage($uid),'documents'=>self::count_table($wpdb->prefix.'zccng_documents','user_id=%d',$uid),'forms'=>self::count_table($wpdb->prefix.'zccng_form_assignments','user_id=%d',$uid),'training'=>self::count_table($wpdb->prefix.'zccng_academy_assignments','user_id=%d',$uid),'messages'=>self::count_table($wpdb->prefix.'zccng_messages','recipient_id=%d',$uid),'security_reports'=>self::count_table($wpdb->prefix.'zccng_security_reports','reported_by=%d',$uid),'archives'=>self::count_table($wpdb->prefix.'zccng_archive_records','user_id=%d',$uid)];}
 public static function render_identity($uid){$u=get_userdata($uid);if(!$u)return '<div class="zccng-empty">Identity unavailable.</div>';$snap=self::snapshot($uid);$events=self::timeline($uid,50);$html='<div class="zccng-lifecycle-identity"><div><strong>'.esc_html($u->display_name).'</strong><small>Continuous identity #'.(int)$uid.' · '.esc_html(self::stages()[$snap['stage']]??ucwords($snap['stage'])).'</small></div><div class="zccng-lifecycle-counts"><span>Documents <b>'.(int)$snap['documents'].'</b></span><span>Forms <b>'.(int)$snap['forms'].'</b></span><span>Training <b>'.(int)$snap['training'].'</b></span><span>Inbox <b>'.(int)$snap['messages'].'</b></span><span>Security <b>'.(int)$snap['security_reports'].'</b></span><span>Archive <b>'.(int)$snap['archives'].'</b></span></div></div><div class="zccng-lifecycle-timeline">';if(!$events)$html.='<div class="zccng-empty">No lifecycle events recorded yet.</div>';foreach($events as $event)$html.='<article><i></i><div><strong>'.esc_html($event['summary']).'</strong><small>'.esc_html(ucwords(str_replace('_',' ',$event['event_type'])).' · '.$event['created_at']).'</small></div></article>';$html.='</div>';return $html;}
 public function change_stage(){if(!Permissions::instance()->can('zccng_manage_lifecycle'))wp_die('Forbidden',403);check_admin_referer('zccng_lifecycle_stage');$uid=absint($_POST['user_id']??0);$stage=sanitize_key($_POST['stage']??'');if(!$uid||!get_userdata($uid)||!isset(self::stages()[$stage]))wp_die('Invalid lifecycle transition.');$before=self::current_stage($uid);update_user_meta($uid,'zccng_lifecycle_stage',$stage);$u=new \WP_User($uid);if($stage==='candidate')$u->set_role('zccng_candidate');elseif(in_array($stage,['onboarding','employee','leave'],true))$u->set_role('zccng_staff');if(in_array($stage,['former_employee','alumni','retired','archived'],true))update_user_meta($uid,'zccng_account_restricted',1);else delete_user_meta($uid,'zccng_account_restricted');self::record($uid,'stage_changed','Lifecycle stage changed from '.self::stages()[$before].' to '.self::stages()[$stage],['from'=>$before,'to'=>$stage]);Audit::log('lifecycle_stage_changed','Workforce lifecycle stage changed',['user_id'=>$uid,'from'=>$before,'to'=>$stage]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr'));exit;}
 public function role_changed($uid,$role,$old_roles){self::record($uid,'role_changed','WordPress role changed to '.$role,['old_roles'=>$old_roles,'new_role'=>$role]);}
}
