<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Archives{
 private static $instance;
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_post_zccng_archive_record',[$this,'save']);add_action('admin_post_zccng_archive_restore',[$this,'restore']);}
 public static function statuses(){return ['archived','talent_pool','former_employee','retired','alumni','suspended','hold','pending_deletion','dormant'];}
 private static function table(){global $wpdb;return $wpdb->prefix.'zccng_archive_records';}
 public static function records($status='',$limit=200){global $wpdb;$limit=max(1,min(500,(int)$limit));$sql='SELECT * FROM '.self::table();if($status&&in_array($status,self::statuses(),true))$sql.=$wpdb->prepare(' WHERE archive_status=%s',$status);$sql.=' ORDER BY updated_at DESC LIMIT '.$limit;return (array)$wpdb->get_results($sql,ARRAY_A);}
 public static function counts(){global $wpdb;$rows=(array)$wpdb->get_results('SELECT archive_status,COUNT(*) total FROM '.self::table().' GROUP BY archive_status',ARRAY_A);$out=array_fill_keys(self::statuses(),0);$out['total']=0;foreach($rows as $row){$k=sanitize_key($row['archive_status']);if(isset($out[$k]))$out[$k]=(int)$row['total'];$out['total']+=(int)$row['total'];}return $out;}
 public static function get($uid){global $wpdb;return $wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table().' WHERE user_id=%d',$uid),ARRAY_A);}
 public function save(){if(!Permissions::instance()->can('zccng_manage_archives'))wp_die('Forbidden',403);check_admin_referer('zccng_archive_record');$uid=absint($_POST['user_id']??0);$status=sanitize_key($_POST['archive_status']??'archived');if(!$uid||!get_userdata($uid)||!in_array($status,self::statuses(),true))wp_die('Invalid archive record.');$existing=self::get($uid);$now=current_time('mysql',true);$data=['user_id'=>$uid,'record_type'=>sanitize_key($_POST['record_type']??'candidate'),'archive_status'=>$status,'archive_reason'=>sanitize_text_field($_POST['archive_reason']??''),'notes'=>sanitize_textarea_field($_POST['notes']??''),'tags'=>sanitize_text_field($_POST['tags']??''),'rehire_status'=>sanitize_key($_POST['rehire_status']??'review'),'retention_until'=>sanitize_text_field($_POST['retention_until']??''),'hold_reason'=>sanitize_text_field($_POST['hold_reason']??''),'updated_by'=>get_current_user_id(),'updated_at'=>$now];global $wpdb;$t=self::table();if($existing)$wpdb->update($t,$data,['user_id'=>$uid]);else{$data['created_at']=$now;$wpdb->insert($t,$data);}update_user_meta($uid,'zccng_archive_status',$status);if(in_array($status,['suspended','hold','pending_deletion','archived'],true))update_user_meta($uid,'zccng_account_restricted',1);else delete_user_meta($uid,'zccng_account_restricted');$ct=$wpdb->prefix.'zccng_candidates';if($wpdb->get_var($wpdb->prepare("SHOW TABLES LIKE %s",$ct))===$ct&&in_array($status,['archived','talent_pool','suspended'],true))$wpdb->update($ct,['status'=>$status,'updated_at'=>$now],['user_id'=>$uid]);Audit::log('archive_status_changed','Archive lifecycle status changed',['user_id'=>$uid,'archive_status'=>$status,'reason'=>$data['archive_reason']]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr'));exit;}
 public function restore(){if(!Permissions::instance()->can('zccng_manage_archives'))wp_die('Forbidden',403);$uid=absint($_GET['user_id']??0);check_admin_referer('zccng_archive_restore_'.$uid);if(!$uid||!get_userdata($uid))wp_die('Invalid record.');global $wpdb;$wpdb->delete(self::table(),['user_id'=>$uid]);delete_user_meta($uid,'zccng_archive_status');delete_user_meta($uid,'zccng_account_restricted');$u=new \WP_User($uid);$target=sanitize_key($_GET['target']??'candidate');if($target==='staff')$u->set_role('zccng_staff');elseif($target==='candidate')$u->set_role('zccng_candidate');$ct=$wpdb->prefix.'zccng_candidates';if($wpdb->get_var($wpdb->prepare("SHOW TABLES LIKE %s",$ct))===$ct)$wpdb->update($ct,['status'=>$target==='staff'?'hired':'reviewing','updated_at'=>current_time('mysql',true)],['user_id'=>$uid]);Audit::log('archive_record_restored','Archived workforce record restored',['user_id'=>$uid,'target'=>$target]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr'));exit;}
}
