<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Documents{
 private static $instance;
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_post_zccng_document_upload',[$this,'upload']);add_action('admin_post_zccng_document_review',[$this,'review']);add_action('admin_post_zccng_document_download',[$this,'download']);add_action('admin_post_zccng_document_archive',[$this,'archive']);}
 public static function categories(){return ['resume'=>'Resume','contract'=>'Contract','certificate'=>'Certificate','policy'=>'Policy','identity'=>'Identity','employment'=>'Employment','general'=>'General'];}
 private static function table(){global $wpdb;return $wpdb->prefix.'zccng_documents';}
 public static function mine($uid=0){global $wpdb;$uid=$uid?:get_current_user_id();return (array)$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::table().' WHERE user_id=%d AND status<>%s ORDER BY created_at DESC',$uid,'archived'),ARRAY_A);}
 public static function review_queue($limit=100){global $wpdb;$limit=max(1,min(200,(int)$limit));return (array)$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::table()." WHERE status IN ('pending','replaced') ORDER BY created_at DESC LIMIT %d",$limit),ARRAY_A);}
 public static function counts(){global $wpdb;$t=self::table();$rows=(array)$wpdb->get_results("SELECT status,COUNT(*) total FROM $t GROUP BY status",ARRAY_A);$out=['total'=>0,'pending'=>0,'approved'=>0,'rejected'=>0,'replaced'=>0,'archived'=>0];foreach($rows as $row){$key=sanitize_key($row['status']);$out[$key]=(int)$row['total'];$out['total']+=(int)$row['total'];}return $out;}
 public static function render_mine(){if(!is_user_logged_in())return '';$rows=self::mine();$html='<div class="zccng-table-wrap"><table class="zccng-table"><thead><tr><th>Document</th><th>Category</th><th>Version</th><th>Status</th><th>Updated</th><th>Action</th></tr></thead><tbody>';if(!$rows)$html.='<tr><td colspan="6">No documents uploaded.</td></tr>';foreach($rows as $d){$url=wp_nonce_url(admin_url('admin-post.php?action=zccng_document_download&id='.(int)$d['id']),'zccng_document_download_'.(int)$d['id']);$html.='<tr><td>'.esc_html($d['title']).'</td><td>'.esc_html(ucwords($d['category'])).'</td><td>v'.(int)$d['version'].'</td><td>'.esc_html(ucwords($d['status'])).'</td><td>'.esc_html($d['updated_at']).'</td><td><a href="'.esc_url($url).'">Download</a></td></tr>';}$html.='</tbody></table></div>';return $html;}
 public function upload(){if(!is_user_logged_in())wp_die('Authentication required.');check_admin_referer('zccng_document_upload');$uid=get_current_user_id();if(!empty($_POST['user_id'])&&Permissions::instance()->can('zccng_manage_documents'))$uid=absint($_POST['user_id']);if(!$uid||!get_userdata($uid))wp_die('Invalid record owner.');if(empty($_FILES['document_file']['name']))wp_die('Choose a document.');require_once ABSPATH.'wp-admin/includes/file.php';$allowed=['pdf'=>'application/pdf','doc'=>'application/msword','docx'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document','txt'=>'text/plain','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png'];$upload=wp_handle_upload($_FILES['document_file'],['test_form'=>false,'mimes'=>$allowed]);if(!empty($upload['error']))wp_die(esc_html($upload['error']));global $wpdb;$t=self::table();$category=array_key_exists(sanitize_key($_POST['category']??''),self::categories())?sanitize_key($_POST['category']):'general';$title=sanitize_text_field($_POST['title']??pathinfo($_FILES['document_file']['name'],PATHINFO_FILENAME));$replace=absint($_POST['replace_id']??0);$version=1;if($replace){$old=$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE id=%d",$replace),ARRAY_A);if($old&&((int)$old['user_id']===$uid||Permissions::instance()->can('zccng_manage_documents'))){$version=(int)$old['version']+1;$wpdb->update($t,['status'=>'replaced','updated_at'=>current_time('mysql',true)],['id'=>$replace]);}}$ok=$wpdb->insert($t,['user_id'=>$uid,'title'=>$title,'category'=>$category,'file_name'=>sanitize_file_name($_FILES['document_file']['name']),'file_path'=>wp_normalize_path($upload['file']),'mime_type'=>sanitize_mime_type($upload['type']),'version'=>$version,'replaces_id'=>$replace,'status'=>'pending','uploaded_by'=>get_current_user_id(),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)]);if(!$ok)wp_die('Unable to save document record.');Audit::log('document_uploaded','Workforce document uploaded',['document_id'=>$wpdb->insert_id,'user_id'=>$uid,'category'=>$category]);wp_safe_redirect(wp_get_referer()?:admin_url());exit;}
 public function review(){if(!Permissions::instance()->can('zccng_manage_documents'))wp_die('Forbidden',403);check_admin_referer('zccng_document_review');$id=absint($_POST['document_id']??0);$status=sanitize_key($_POST['status']??'');if(!in_array($status,['approved','rejected','pending'],true))wp_die('Invalid status.');global $wpdb;$wpdb->update(self::table(),['status'=>$status,'reviewed_by'=>get_current_user_id(),'reviewed_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)],['id'=>$id]);Audit::log('document_'.$status,'Workforce document reviewed',['document_id'=>$id]);wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=zccng-hr'));exit;}
 public function archive(){if(!Permissions::instance()->can('zccng_manage_documents'))wp_die('Forbidden',403);$id=absint($_GET['id']??0);check_admin_referer('zccng_document_archive_'.$id);global $wpdb;$wpdb->update(self::table(),['status'=>'archived','updated_at'=>current_time('mysql',true)],['id'=>$id]);Audit::log('document_archived','Workforce document archived',['document_id'=>$id]);wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=zccng-hr'));exit;}
 public function download(){if(!is_user_logged_in())wp_die('Authentication required.');$id=absint($_GET['id']??0);check_admin_referer('zccng_document_download_'.$id);global $wpdb;$d=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table().' WHERE id=%d',$id),ARRAY_A);if(!$d)wp_die('Document not found.',404);if((int)$d['user_id']!==get_current_user_id()&&!Permissions::instance()->can('zccng_manage_documents'))wp_die('Forbidden',403);$file=wp_normalize_path($d['file_path']);$uploads=wp_normalize_path(wp_get_upload_dir()['basedir']);if(strpos($file,$uploads)!==0||!is_readable($file))wp_die('Document file unavailable.',404);Audit::log('document_downloaded','Workforce document downloaded',['document_id'=>$id]);nocache_headers();header('Content-Type: '.($d['mime_type']?:'application/octet-stream'));header('Content-Disposition: attachment; filename="'.basename($d['file_name']).'"');header('Content-Length: '.filesize($file));readfile($file);exit;}
}
