<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Academy{
 private static $instance;
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_post_zccng_academy_course',[$this,'save_course']);add_action('admin_post_zccng_academy_assign',[$this,'assign']);add_action('admin_post_zccng_academy_progress',[$this,'progress']);add_action('admin_post_zccng_academy_review',[$this,'review']);}
 private static function courses_table(){global $wpdb;return $wpdb->prefix.'zccng_academy_courses';}
 private static function assignments_table(){global $wpdb;return $wpdb->prefix.'zccng_academy_assignments';}
 public static function categories(){return ['security'=>'Security','compliance'=>'Compliance','safety'=>'Safety','policy'=>'Policies','leadership'=>'Leadership','management'=>'Management','customer_service'=>'Customer Service','technical'=>'Technical Skills','general'=>'General'];}
 public static function courses($published_only=false){global $wpdb;$sql='SELECT * FROM '.self::courses_table();if($published_only)$sql.=" WHERE status='published'";$sql.=' ORDER BY updated_at DESC';return (array)$wpdb->get_results($sql,ARRAY_A);}
 public static function assignments($uid){global $wpdb;$a=self::assignments_table();$c=self::courses_table();return (array)$wpdb->get_results($wpdb->prepare("SELECT a.*,c.title,c.description,c.category,c.required,c.duration_minutes,c.certificate_name FROM $a a JOIN $c c ON c.id=a.course_id WHERE a.user_id=%d ORDER BY FIELD(a.status,'overdue','assigned','in_progress','completed','waived'),a.due_at ASC",$uid),ARRAY_A);}
 public static function review_queue($limit=150){global $wpdb;$a=self::assignments_table();$c=self::courses_table();$limit=max(1,min(300,(int)$limit));return (array)$wpdb->get_results($wpdb->prepare("SELECT a.*,c.title,c.category,c.required FROM $a a JOIN $c c ON c.id=a.course_id ORDER BY a.updated_at DESC LIMIT %d",$limit),ARRAY_A);}
 public static function counts(){global $wpdb;$a=self::assignments_table();$c=self::courses_table();return ['courses'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $c WHERE status='published'"),'assigned'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $a WHERE status IN ('assigned','in_progress','overdue')"),'completed'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $a WHERE status='completed'"),'overdue'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $a WHERE status='overdue' OR (status IN ('assigned','in_progress') AND due_at IS NOT NULL AND due_at<UTC_TIMESTAMP())")];}
 public static function render_mine(){if(!is_user_logged_in())return '';$rows=self::assignments(get_current_user_id());$html='<div class="zccng-table-wrap"><table class="zccng-table"><thead><tr><th>Course</th><th>Category</th><th>Required</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody>';if(!$rows)$html.='<tr><td colspan="6">No training has been assigned.</td></tr>';foreach($rows as $row){$status=$row['status'];if(in_array($status,['assigned','in_progress'],true)&&$row['due_at']&&strtotime($row['due_at'])<time())$status='overdue';$html.='<tr><td><strong>'.esc_html($row['title']).'</strong><br><small>'.esc_html($row['description']).'</small></td><td>'.esc_html(self::categories()[$row['category']]??ucwords($row['category'])).'</td><td>'.($row['required']?'Yes':'No').'</td><td>'.esc_html($row['due_at']?:'No deadline').'</td><td>'.esc_html(ucwords(str_replace('_',' ',$status))).'</td><td>';if(!in_array($status,['completed','waived'],true)){$html.='<form class="zccng-inline-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="zccng_academy_progress"><input type="hidden" name="assignment_id" value="'.(int)$row['id'].'">'.wp_nonce_field('zccng_academy_progress','_wpnonce',true,false).'<button name="status" value="in_progress">Start</button> · <button name="status" value="completed">Complete</button></form>';}else{$html.='Complete';}$html.='</td></tr>';}$html.='</tbody></table></div>';return $html;}
 public function save_course(){if(!Permissions::instance()->can('zccng_manage_academy'))wp_die('Forbidden',403);check_admin_referer('zccng_academy_course');$title=sanitize_text_field($_POST['title']??'');if(!$title)wp_die('Course title required.');$category=sanitize_key($_POST['category']??'general');if(!array_key_exists($category,self::categories()))$category='general';global $wpdb;$wpdb->insert(self::courses_table(),['title'=>$title,'description'=>sanitize_textarea_field($_POST['description']??''),'category'=>$category,'required'=>!empty($_POST['required'])?1:0,'duration_minutes'=>absint($_POST['duration_minutes']??0),'certificate_name'=>sanitize_text_field($_POST['certificate_name']??''),'status'=>!empty($_POST['publish'])?'published':'draft','created_by'=>get_current_user_id(),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)]);Audit::log('academy_course_created','Workforce Academy course created',['course_id'=>$wpdb->insert_id,'category'=>$category]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr'));exit;}
 public function assign(){if(!Permissions::instance()->can('zccng_manage_academy'))wp_die('Forbidden',403);check_admin_referer('zccng_academy_assign');$course=absint($_POST['course_id']??0);$uid=absint($_POST['user_id']??0);if(!$course||!$uid||!get_userdata($uid))wp_die('Invalid assignment.');global $wpdb;$now=current_time('mysql',true);$wpdb->replace(self::assignments_table(),['course_id'=>$course,'user_id'=>$uid,'status'=>'assigned','assigned_by'=>get_current_user_id(),'due_at'=>sanitize_text_field($_POST['due_at']??''),'progress_percent'=>0,'completed_at'=>null,'reviewed_by'=>0,'reviewed_at'=>null,'created_at'=>$now,'updated_at'=>$now]);Audit::log('academy_course_assigned','Training assigned',['course_id'=>$course,'user_id'=>$uid]);if(class_exists(Communications::class))Communications::notify_user($uid,'Training assigned','A Workforce Academy course has been assigned to you.','training','important');wp_safe_redirect(admin_url('admin.php?page=zccng-hr'));exit;}
 public function progress(){if(!is_user_logged_in())wp_die('Authentication required.');check_admin_referer('zccng_academy_progress');$id=absint($_POST['assignment_id']??0);$status=sanitize_key($_POST['status']??'in_progress');if(!in_array($status,['in_progress','completed'],true))wp_die('Invalid status.');global $wpdb;$table=self::assignments_table();$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id=%d",$id),ARRAY_A);if(!$row||(int)$row['user_id']!==get_current_user_id())wp_die('Forbidden',403);$wpdb->update($table,['status'=>$status,'progress_percent'=>$status==='completed'?100:max(1,(int)$row['progress_percent']),'completed_at'=>$status==='completed'?current_time('mysql',true):null,'updated_at'=>current_time('mysql',true)],['id'=>$id]);Audit::log('academy_'.$status,'Training progress updated',['assignment_id'=>$id]);wp_safe_redirect(admin_url('admin.php?page=zccng-staff'));exit;}
 public function review(){if(!Permissions::instance()->can('zccng_manage_academy'))wp_die('Forbidden',403);check_admin_referer('zccng_academy_review');$id=absint($_POST['assignment_id']??0);$status=sanitize_key($_POST['status']??'assigned');if(!in_array($status,['assigned','in_progress','completed','waived','overdue'],true))wp_die('Invalid status.');global $wpdb;$wpdb->update(self::assignments_table(),['status'=>$status,'progress_percent'=>$status==='completed'?100:absint($_POST['progress_percent']??0),'reviewed_by'=>get_current_user_id(),'reviewed_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)],['id'=>$id]);Audit::log('academy_assignment_reviewed','Training assignment reviewed',['assignment_id'=>$id,'status'=>$status]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr'));exit;}
}
