<?php
namespace ZCCNG;
if(!defined('ABSPATH'))exit;
final class Forms{
 private static $instance;
 public static function instance(){if(!self::$instance){self::$instance=new self();self::$instance->hooks();}return self::$instance;}
 private function hooks(){add_action('admin_post_zccng_form_template',[$this,'save_template']);add_action('admin_post_zccng_form_assign',[$this,'assign']);add_action('admin_post_zccng_form_submit',[$this,'submit']);add_action('admin_post_zccng_form_review',[$this,'review']);}
 public static function types(){return ['text','email','tel','number','date','select','checkbox','textarea','url'];}
 public static function parse_fields($text){$out=[];foreach(preg_split('/\R/',trim((string)$text)) as $line){$line=trim($line);if(!$line)continue;$p=array_map('trim',explode('|',$line));$label=sanitize_text_field($p[0]??'');$type=sanitize_key($p[1]??'text');if(!$label||!in_array($type,self::types(),true))continue;$out[]=['key'=>sanitize_key($p[5]??$label),'label'=>$label,'type'=>$type,'required'=>in_array(strtolower($p[2]??''),['required','yes','1'],true),'readonly'=>in_array(strtolower($p[3]??''),['readonly','yes','1'],true),'options'=>array_values(array_filter(array_map('sanitize_text_field',explode(',',(string)($p[4]??'')))))];}return $out;}
 public static function templates(){global $wpdb;return (array)$wpdb->get_results("SELECT * FROM {$wpdb->prefix}zccng_form_templates ORDER BY updated_at DESC",ARRAY_A);}
 public static function assignments($uid){global $wpdb;$a=$wpdb->prefix.'zccng_form_assignments';$t=$wpdb->prefix.'zccng_form_templates';$s=$wpdb->prefix.'zccng_form_submissions';return (array)$wpdb->get_results($wpdb->prepare("SELECT a.*,t.title,t.description,t.fields_json,t.version,s.id submission_id,s.status submission_status,s.values_json FROM $a a JOIN $t t ON t.id=a.template_id LEFT JOIN $s s ON s.assignment_id=a.id WHERE a.user_id=%d AND a.status='active' ORDER BY a.created_at DESC",$uid),ARRAY_A);}
 public static function submissions($limit=100){global $wpdb;$s=$wpdb->prefix.'zccng_form_submissions';$t=$wpdb->prefix.'zccng_form_templates';$a=$wpdb->prefix.'zccng_form_assignments';$limit=max(1,min(500,(int)$limit));return (array)$wpdb->get_results("SELECT s.*,t.title,a.user_id FROM $s s JOIN $a a ON a.id=s.assignment_id JOIN $t t ON t.id=a.template_id ORDER BY s.updated_at DESC LIMIT $limit",ARRAY_A);}
 public static function summary(){global $wpdb;$t=$wpdb->prefix.'zccng_form_templates';$a=$wpdb->prefix.'zccng_form_assignments';$s=$wpdb->prefix.'zccng_form_submissions';return ['templates'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE status='published'"),'assigned'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $a WHERE status='active'"),'submitted'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $s WHERE status='submitted'"),'revision'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $s WHERE status='revision_requested'")];}
 public static function render_user_forms($uid){$rows=self::assignments($uid);if(!$rows)return '<div class="zccng-empty">No forms are assigned.</div>';$o='';foreach($rows as $row){$fields=json_decode($row['fields_json'],true)?:[];$values=json_decode($row['values_json']??'{}',true)?:[];$status=$row['submission_status']?:'assigned';$o.='<section><h3>'.esc_html($row['title']).'</h3><p>'.esc_html($row['description']).'</p><p><b>Status:</b> '.esc_html(ucwords(str_replace('_',' ',$status))).'</p><form class="zccng-broadcast-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="zccng_form_submit"><input type="hidden" name="assignment_id" value="'.(int)$row['id'].'">'.wp_nonce_field('zccng_form_submit_'.(int)$row['id'],'_wpnonce',true,false);foreach($fields as $f){$key=$f['key'];$val=$values[$key]??'';$req=!empty($f['required'])?' required':'';$ro=!empty($f['readonly'])?' readonly':'';$o.='<label>'.esc_html($f['label']);if($f['type']==='textarea')$o.='<textarea name="fields['.esc_attr($key).']"'.$req.$ro.'>'.esc_textarea($val).'</textarea>';elseif($f['type']==='select'){$o.='<select name="fields['.esc_attr($key).']"'.$req.'><option value="">Select</option>';foreach($f['options'] as $opt)$o.='<option value="'.esc_attr($opt).'" '.selected($val,$opt,false).'>'.esc_html($opt).'</option>';$o.='</select>';}elseif($f['type']==='checkbox')$o.='<input type="checkbox" name="fields['.esc_attr($key).']" value="1" '.checked($val,'1',false).$req.'>';else $o.='<input type="'.esc_attr($f['type']).'" name="fields['.esc_attr($key).']" value="'.esc_attr($val).'"'.$req.$ro.'>';$o.='</label>';}$o.='<button class="zccng-button" type="submit">Submit form</button></form></section>'; }return $o;}
 public function save_template(){if(!Permissions::instance()->can('zccng_manage_forms'))wp_die('Permission denied',403);check_admin_referer('zccng_form_template');$title=sanitize_text_field($_POST['title']??'');$fields=self::parse_fields(wp_unslash($_POST['fields']??''));if(!$title||!$fields)wp_die('A title and at least one valid field are required.',400);global $wpdb;$t=$wpdb->prefix.'zccng_form_templates';$now=current_time('mysql',true);$wpdb->insert($t,['title'=>$title,'description'=>sanitize_textarea_field($_POST['description']??''),'status'=>isset($_POST['publish'])?'published':'draft','version'=>1,'fields_json'=>wp_json_encode($fields),'conditions_json'=>wp_json_encode(['country'=>sanitize_text_field($_POST['country']??''),'position'=>sanitize_text_field($_POST['position']??''),'department'=>sanitize_text_field($_POST['department']??''),'employment_type'=>sanitize_text_field($_POST['employment_type']??''),'role'=>sanitize_key($_POST['role']??'')]),'created_by'=>get_current_user_id(),'created_at'=>$now,'updated_at'=>$now]);Audit::log('form_template_created','Smart Form template created',['template_id'=>(int)$wpdb->insert_id]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr&form_created=1'));exit;}
 public function assign(){if(!Permissions::instance()->can('zccng_manage_forms'))wp_die('Permission denied',403);check_admin_referer('zccng_form_assign');$template=absint($_POST['template_id']??0);$uid=absint($_POST['user_id']??0);if(!$template||!$uid||!get_userdata($uid))wp_die('Valid template and user are required.',400);global $wpdb;$t=$wpdb->prefix.'zccng_form_assignments';$wpdb->replace($t,['template_id'=>$template,'user_id'=>$uid,'status'=>'active','assigned_by'=>get_current_user_id(),'due_at'=>sanitize_text_field($_POST['due_at']??'')?:null,'created_at'=>current_time('mysql',true)],['%d','%d','%s','%d','%s','%s']);$nid=$wpdb->prefix.'zccng_notifications';$wpdb->insert($nid,['user_id'=>$uid,'title'=>'New form assigned','message'=>'A workforce form is ready for completion.','category'=>'hr','priority'=>'important','is_read'=>0,'created_at'=>current_time('mysql',true)]);Audit::log('form_assigned','Smart Form assigned',['template_id'=>$template,'user_id'=>$uid]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr&form_assigned=1'));exit;}
 public function submit(){if(!is_user_logged_in())wp_die('Permission denied',403);$id=absint($_POST['assignment_id']??0);check_admin_referer('zccng_form_submit_'.$id);global $wpdb;$a=$wpdb->prefix.'zccng_form_assignments';$assign=$wpdb->get_row($wpdb->prepare("SELECT * FROM $a WHERE id=%d AND user_id=%d",$id,get_current_user_id()),ARRAY_A);if(!$assign)wp_die('Assignment not found.',404);$raw=(array)($_POST['fields']??[]);$values=[];foreach($raw as $k=>$v)$values[sanitize_key($k)]=is_array($v)?array_map('sanitize_text_field',$v):sanitize_textarea_field($v);$s=$wpdb->prefix.'zccng_form_submissions';$existing=$wpdb->get_var($wpdb->prepare("SELECT id FROM $s WHERE assignment_id=%d",$id));$data=['assignment_id'=>$id,'values_json'=>wp_json_encode($values),'status'=>'submitted','submitted_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)];if($existing)$wpdb->update($s,$data,['id'=>$existing]);else{$data['created_at']=current_time('mysql',true);$wpdb->insert($s,$data);}Audit::log('form_submitted','Smart Form submitted',['assignment_id'=>$id]);wp_safe_redirect(admin_url('admin.php?page=zccng-staff-hub&form_submitted=1'));exit;}
 public function review(){if(!Permissions::instance()->can('zccng_manage_forms'))wp_die('Permission denied',403);$id=absint($_GET['id']??0);$status=sanitize_key($_GET['status']??'');check_admin_referer('zccng_form_review_'.$id);if(!$id||!in_array($status,['approved','rejected','revision_requested'],true))wp_die('Invalid request',400);global $wpdb;$t=$wpdb->prefix.'zccng_form_submissions';$wpdb->update($t,['status'=>$status,'reviewed_by'=>get_current_user_id(),'reviewed_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)],['id'=>$id]);Audit::log('form_'.$status,'Smart Form review completed',['submission_id'=>$id]);wp_safe_redirect(admin_url('admin.php?page=zccng-hr'));exit;}
}
